/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Account
 */
export interface Account {
  /**
   *
   * @type {string}
   * @memberof Account
   */
  id: string;
  /**
   *
   * @type {number}
   * @memberof Account
   */
  hours: number;
  /**
   *
   * @type {Date}
   * @memberof Account
   */
  unlimitedDue?: Date;
  /**
   *
   * @type {Date}
   * @memberof Account
   */
  createAt: Date;
}

export function AccountFromJSON(json: any): Account {
  return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    hours: json["hours"],
    unlimitedDue: !exists(json, "unlimitedDue") ? undefined : new Date(json["unlimitedDue"]),
    createAt: new Date(json["createAt"])
  };
}

export function AccountToJSON(value?: Account | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    hours: value.hours === undefined ? null : value.hours,
    unlimitedDue: value.unlimitedDue === undefined ? null : value.unlimitedDue.toISOString(),
    createAt: value.createAt.toISOString()
  };
}
