/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminName
 */
export interface AdminName {
  /**
   *
   * @type {string}
   * @memberof AdminName
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AdminName
   */
  name: string;
}

export function AdminNameFromJSON(json: any): AdminName {
  return AdminNameFromJSONTyped(json, false);
}

export function AdminNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminName {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"]
  };
}

export function AdminNameToJSON(value?: AdminName | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    name: value.name === undefined ? null : value.name
  };
}
