/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdministrationHistory
 */
export interface AdministrationHistory {
  /**
   *
   * @type {string}
   * @memberof AdministrationHistory
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AdministrationHistory
   */
  accountId: string;
  /**
   *
   * @type {string}
   * @memberof AdministrationHistory
   */
  ticketId: string;
  /**
   *
   * @type {string}
   * @memberof AdministrationHistory
   */
  reason: string;
  /**
   *
   * @type {number}
   * @memberof AdministrationHistory
   */
  hours: number;
  /**
   *
   * @type {string}
   * @memberof AdministrationHistory
   */
  adminId: string;
  /**
   *
   * @type {Date}
   * @memberof AdministrationHistory
   */
  createdAt: Date;
}

export function AdministrationHistoryFromJSON(json: any): AdministrationHistory {
  return AdministrationHistoryFromJSONTyped(json, false);
}

export function AdministrationHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdministrationHistory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    accountId: json["accountId"],
    ticketId: json["ticketId"],
    reason: json["reason"],
    hours: json["hours"],
    adminId: json["adminId"],
    createdAt: new Date(json["createdAt"])
  };
}

export function AdministrationHistoryToJSON(value?: AdministrationHistory | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    accountId: value.accountId === undefined ? null : value.accountId,
    ticketId: value.ticketId === undefined ? null : value.ticketId,
    reason: value.reason === undefined ? null : value.reason,
    hours: value.hours === undefined ? null : value.hours,
    adminId: value.adminId === undefined ? null : value.adminId,
    createdAt: value.createdAt.toISOString()
  };
}
