/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminCheckoutSessionCreateDTO
 */
export interface AdminCheckoutSessionCreateDTO {
  /**
   *
   * @type {string}
   * @memberof AdminCheckoutSessionCreateDTO
   */
  userId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AdminCheckoutSessionCreateDTO
   */
  invoiceIds: Array<string>;
}

export function AdminCheckoutSessionCreateDTOFromJSON(json: any): AdminCheckoutSessionCreateDTO {
  return AdminCheckoutSessionCreateDTOFromJSONTyped(json, false);
}

export function AdminCheckoutSessionCreateDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdminCheckoutSessionCreateDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json["userId"],
    invoiceIds: json["invoiceIds"]
  };
}

export function AdminCheckoutSessionCreateDTOToJSON(value?: AdminCheckoutSessionCreateDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userId: value.userId === undefined ? null : value.userId,
    invoiceIds: value.invoiceIds === undefined ? null : value.invoiceIds
  };
}
