/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdminBuyAdministrationTariff
 */
export interface AdminBuyAdministrationTariff {
  /**
   *
   * @type {string}
   * @memberof AdminBuyAdministrationTariff
   */
  tariffId: string;
}

export function AdminBuyAdministrationTariffFromJSON(json: any): AdminBuyAdministrationTariff {
  return AdminBuyAdministrationTariffFromJSONTyped(json, false);
}

export function AdminBuyAdministrationTariffFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdminBuyAdministrationTariff {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tariffId: json["tariffId"]
  };
}

export function AdminBuyAdministrationTariffToJSON(value?: AdminBuyAdministrationTariff | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    tariffId: value.tariffId === undefined ? null : value.tariffId
  };
}
