/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdministrationTariff
 */
export interface AdministrationTariff {
  /**
   *
   * @type {string}
   * @memberof AdministrationTariff
   */
  price: string;
  /**
   *
   * @type {string}
   * @memberof AdministrationTariff
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AdministrationTariff
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof AdministrationTariff
   */
  hours: number;
  /**
   *
   * @type {boolean}
   * @memberof AdministrationTariff
   */
  unlimited: boolean;
}

export function AdministrationTariffFromJSON(json: any): AdministrationTariff {
  return AdministrationTariffFromJSONTyped(json, false);
}

export function AdministrationTariffFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdministrationTariff {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    price: json["price"],
    id: json["id"],
    name: json["name"],
    hours: json["hours"],
    unlimited: json["unlimited"]
  };
}

export function AdministrationTariffToJSON(value?: AdministrationTariff | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    price: value.price === undefined ? null : value.price,
    id: value.id === undefined ? null : value.id,
    name: value.name === undefined ? null : value.name,
    hours: value.hours === undefined ? null : value.hours,
    unlimited: value.unlimited === undefined ? null : value.unlimited
  };
}
