/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthHistory
 */
export interface AuthHistory {
  /**
   *
   * @type {Date}
   * @memberof AuthHistory
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof AuthHistory
   */
  os: string;
  /**
   *
   * @type {string}
   * @memberof AuthHistory
   */
  browser: string;
  /**
   *
   * @type {string}
   * @memberof AuthHistory
   */
  ip: string;
}

export function AuthHistoryFromJSON(json: any): AuthHistory {
  return AuthHistoryFromJSONTyped(json, false);
}

export function AuthHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthHistory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    createdAt: new Date(json["createdAt"]),
    os: json["os"],
    browser: json["browser"],
    ip: json["ip"]
  };
}

export function AuthHistoryToJSON(value?: AuthHistory | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    createdAt: value.createdAt.toISOString(),
    os: value.os === undefined ? null : value.os,
    browser: value.browser === undefined ? null : value.browser,
    ip: value.ip === undefined ? null : value.ip
  };
}
