/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BalanceTransactionDTO
 */
export interface BalanceTransactionDTO {
  /**
   *
   * @type {string}
   * @memberof BalanceTransactionDTO
   */
  userId: string;
  /**
   *
   * @type {Date}
   * @memberof BalanceTransactionDTO
   */
  createdAt: Date;
}

export function BalanceTransactionDTOFromJSON(json: any): BalanceTransactionDTO {
  return BalanceTransactionDTOFromJSONTyped(json, false);
}

export function BalanceTransactionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceTransactionDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json["userId"],
    createdAt: new Date(json["createdAt"])
  };
}

export function BalanceTransactionDTOToJSON(value?: BalanceTransactionDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userId: value.userId === undefined ? null : value.userId,
    createdAt: value.createdAt.toISOString()
  };
}
