/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BalancePayment
 */
export interface BalancePayment {
  /**
   *
   * @type {string}
   * @memberof BalancePayment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BalancePayment
   */
  paymentId: string;
  /**
   *
   * @type {string}
   * @memberof BalancePayment
   */
  status: BalancePaymentStatusEnum;
  /**
   *
   * @type {string}
   * @memberof BalancePayment
   */
  amount: string;
}

export function BalancePaymentFromJSON(json: any): BalancePayment {
  return BalancePaymentFromJSONTyped(json, false);
}

export function BalancePaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalancePayment {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    paymentId: json["paymentId"],
    status: json["status"],
    amount: json["amount"]
  };
}

export function BalancePaymentToJSON(value?: BalancePayment | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    paymentId: value.paymentId === undefined ? null : value.paymentId,
    status: value.status === undefined ? null : value.status,
    amount: value.amount === undefined ? null : value.amount
  };
}

/**
 * @export
 * @enum {string}
 */
export enum BalancePaymentStatusEnum {
  WAIT = "WAIT",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED"
}
