/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BalanceDTO
 */
export interface BalanceDTO {
  /**
   *
   * @type {string}
   * @memberof BalanceDTO
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof BalanceDTO
   */
  balance: string;
}

export function BalanceDTOFromJSON(json: any): BalanceDTO {
  return BalanceDTOFromJSONTyped(json, false);
}

export function BalanceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BalanceDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json["userId"],
    balance: json["balance"]
  };
}

export function BalanceDTOToJSON(value?: BalanceDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userId: value.userId === undefined ? null : value.userId,
    balance: value.balance === undefined ? null : value.balance
  };
}
