/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BillId
 */
export interface BillId {
  /**
   *
   * @type {string}
   * @memberof BillId
   */
  value: string;
}

export function BillIdFromJSON(json: any): BillId {
  return BillIdFromJSONTyped(json, false);
}

export function BillIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"]
  };
}

export function BillIdToJSON(value?: BillId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value === undefined ? null : value.value
  };
}
