/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BitcoinPaymentRate
 */
export interface BitcoinPaymentRate {
  /**
   *
   * @type {string}
   * @memberof BitcoinPaymentRate
   */
  value: string;
}

export function BitcoinPaymentRateFromJSON(json: any): BitcoinPaymentRate {
  return BitcoinPaymentRateFromJSONTyped(json, false);
}

export function BitcoinPaymentRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): BitcoinPaymentRate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"]
  };
}

export function BitcoinPaymentRateToJSON(value?: BitcoinPaymentRate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value === undefined ? null : value.value
  };
}
