/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BitcoinPayment
 */
export interface BitcoinPayment {
  /**
   *
   * @type {string}
   * @memberof BitcoinPayment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof BitcoinPayment
   */
  address: string;
  /**
   *
   * @type {string}
   * @memberof BitcoinPayment
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof BitcoinPayment
   */
  bitcoinAmount: string;
  /**
   *
   * @type {string}
   * @memberof BitcoinPayment
   */
  bitcoinPrice: string;
}

export function BitcoinPaymentFromJSON(json: any): BitcoinPayment {
  return BitcoinPaymentFromJSONTyped(json, false);
}

export function BitcoinPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): BitcoinPayment {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    address: json["address"],
    amount: json["amount"],
    bitcoinAmount: json["bitcoinAmount"],
    bitcoinPrice: json["bitcoinPrice"]
  };
}

export function BitcoinPaymentToJSON(value?: BitcoinPayment | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    address: value.address === undefined ? null : value.address,
    amount: value.amount === undefined ? null : value.amount,
    bitcoinAmount: value.bitcoinAmount === undefined ? null : value.bitcoinAmount,
    bitcoinPrice: value.bitcoinPrice === undefined ? null : value.bitcoinPrice
  };
}
