/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BlockVds
 */
export interface BlockVds {
  /**
   *
   * @type {string}
   * @memberof BlockVds
   */
  reason: string;
}

export function BlockVdsFromJSON(json: any): BlockVds {
  return BlockVdsFromJSONTyped(json, false);
}

export function BlockVdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockVds {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    reason: json["reason"]
  };
}

export function BlockVdsToJSON(value?: BlockVds | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    reason: value.reason === undefined ? null : value.reason
  };
}
