/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BlockAdmin
 */
export interface BlockAdmin {
  /**
   *
   * @type {string}
   * @memberof BlockAdmin
   */
  reason: string;
}

export function BlockAdminFromJSON(json: any): BlockAdmin {
  return BlockAdminFromJSONTyped(json, false);
}

export function BlockAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockAdmin {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    reason: json["reason"]
  };
}

export function BlockAdminToJSON(value?: BlockAdmin | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    reason: value.reason === undefined ? null : value.reason
  };
}
