/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BlockUser
 */
export interface BlockUser {
  /**
   *
   * @type {string}
   * @memberof BlockUser
   */
  reason: string;
}

export function BlockUserFromJSON(json: any): BlockUser {
  return BlockUserFromJSONTyped(json, false);
}

export function BlockUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockUser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    reason: json["reason"]
  };
}

export function BlockUserToJSON(value?: BlockUser | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    reason: value.reason === undefined ? null : value.reason
  };
}
