/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Card
 */
export interface Card {
  /**
   *
   * @type {string}
   * @memberof Card
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  paymentSystem: string;
  /**
   *
   * @type {string}
   * @memberof Card
   */
  mask: string;
}

export function CardFromJSON(json: any): Card {
  return CardFromJSONTyped(json, false);
}

export function CardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Card {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    paymentSystem: json["paymentSystem"],
    mask: json["mask"]
  };
}

export function CardToJSON(value?: Card | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    paymentSystem: value.paymentSystem === undefined ? null : value.paymentSystem,
    mask: value.mask === undefined ? null : value.mask
  };
}
