/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ChangePassword
 */
export interface ChangePassword {
  /**
   *
   * @type {string}
   * @memberof ChangePassword
   */
  oldPassword: string;
  /**
   *
   * @type {string}
   * @memberof ChangePassword
   */
  newPassword: string;
}

export function ChangePasswordFromJSON(json: any): ChangePassword {
  return ChangePasswordFromJSONTyped(json, false);
}

export function ChangePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePassword {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    oldPassword: json["oldPassword"],
    newPassword: json["newPassword"]
  };
}

export function ChangePasswordToJSON(value?: ChangePassword | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    oldPassword: value.oldPassword === undefined ? null : value.oldPassword,
    newPassword: value.newPassword === undefined ? null : value.newPassword
  };
}
