/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  CheckoutSession,
  CheckoutSessionFromJSON,
  CheckoutSessionFromJSONTyped,
  CheckoutSessionToJSON,
  InvoiceDiscount,
  InvoiceDiscountFromJSON,
  InvoiceDiscountFromJSONTyped,
  InvoiceDiscountToJSON
} from "./";

/**
 *
 * @export
 * @interface CheckoutSessionItem
 */
export interface CheckoutSessionItem {
  /**
   *
   * @type {string}
   * @memberof CheckoutSessionItem
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof CheckoutSessionItem
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CheckoutSessionItem
   */
  name: string;
  /**
   *
   * @type {object}
   * @memberof CheckoutSessionItem
   */
  metadata: object;
  /**
   *
   * @type {InvoiceDiscount}
   * @memberof CheckoutSessionItem
   */
  discount?: InvoiceDiscount;
  /**
   *
   * @type {number}
   * @memberof CheckoutSessionItem
   */
  months?: number;
  /**
   *
   * @type {number}
   * @memberof CheckoutSessionItem
   */
  days?: number;
  /**
   *
   * @type {CheckoutSession}
   * @memberof CheckoutSessionItem
   */
  checkoutSession: CheckoutSession;
}

export function CheckoutSessionItemFromJSON(json: any): CheckoutSessionItem {
  return CheckoutSessionItemFromJSONTyped(json, false);
}

export function CheckoutSessionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    amount: json["amount"],
    id: json["id"],
    name: json["name"],
    metadata: json["metadata"],
    discount: !exists(json, "discount") ? undefined : InvoiceDiscountFromJSON(json["discount"]),
    months: !exists(json, "months") ? undefined : json["months"],
    days: !exists(json, "days") ? undefined : json["days"],
    checkoutSession: CheckoutSessionFromJSON(json["checkoutSession"])
  };
}

export function CheckoutSessionItemToJSON(value?: CheckoutSessionItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    amount: value.amount === undefined ? null : value.amount,
    id: value.id === undefined ? null : value.id,
    name: value.name === undefined ? null : value.name,
    metadata: value.metadata,
    discount: InvoiceDiscountToJSON(value.discount),
    months: value.months === undefined ? null : value.months,
    days: value.days === undefined ? null : value.days,
    checkoutSession: CheckoutSessionToJSON(value.checkoutSession)
  };
}
