/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CheckoutSessionCreateDTO
 */
export interface CheckoutSessionCreateDTO {
  /**
   *
   * @type {Array<string>}
   * @memberof CheckoutSessionCreateDTO
   */
  invoiceIds: Array<string>;
}

export function CheckoutSessionCreateDTOFromJSON(json: any): CheckoutSessionCreateDTO {
  return CheckoutSessionCreateDTOFromJSONTyped(json, false);
}

export function CheckoutSessionCreateDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CheckoutSessionCreateDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    invoiceIds: json["invoiceIds"]
  };
}

export function CheckoutSessionCreateDTOToJSON(value?: CheckoutSessionCreateDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    invoiceIds: value.invoiceIds === undefined ? null : value.invoiceIds
  };
}
