/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConfirmEmailChange
 */
export interface ConfirmEmailChange {
  /**
   *
   * @type {string}
   * @memberof ConfirmEmailChange
   */
  code: string;
}

export function ConfirmEmailChangeFromJSON(json: any): ConfirmEmailChange {
  return ConfirmEmailChangeFromJSONTyped(json, false);
}

export function ConfirmEmailChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmailChange {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json["code"]
  };
}

export function ConfirmEmailChangeToJSON(value?: ConfirmEmailChange | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code === undefined ? null : value.code
  };
}
