/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConfirmPhoneChange
 */
export interface ConfirmPhoneChange {
  /**
   *
   * @type {string}
   * @memberof ConfirmPhoneChange
   */
  phone: string;
  /**
   *
   * @type {string}
   * @memberof ConfirmPhoneChange
   */
  code: string;
}

export function ConfirmPhoneChangeFromJSON(json: any): ConfirmPhoneChange {
  return ConfirmPhoneChangeFromJSONTyped(json, false);
}

export function ConfirmPhoneChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPhoneChange {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    phone: json["phone"],
    code: json["code"]
  };
}

export function ConfirmPhoneChangeToJSON(value?: ConfirmPhoneChange | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    phone: value.phone === undefined ? null : value.phone,
    code: value.code === undefined ? null : value.code
  };
}
