/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConfirmEmail
 */
export interface ConfirmEmail {
  /**
   *
   * @type {string}
   * @memberof ConfirmEmail
   */
  code: string;
}

export function ConfirmEmailFromJSON(json: any): ConfirmEmail {
  return ConfirmEmailFromJSONTyped(json, false);
}

export function ConfirmEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmEmail {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json["code"]
  };
}

export function ConfirmEmailToJSON(value?: ConfirmEmail | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code === undefined ? null : value.code
  };
}
