/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ConfirmPasswordRestore
 */
export interface ConfirmPasswordRestore {
  /**
   *
   * @type {string}
   * @memberof ConfirmPasswordRestore
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof ConfirmPasswordRestore
   */
  password: string;
}

export function ConfirmPasswordRestoreFromJSON(json: any): ConfirmPasswordRestore {
  return ConfirmPasswordRestoreFromJSONTyped(json, false);
}

export function ConfirmPasswordRestoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPasswordRestore {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: json["code"],
    password: json["password"]
  };
}

export function ConfirmPasswordRestoreToJSON(value?: ConfirmPasswordRestore | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code === undefined ? null : value.code,
    password: value.password === undefined ? null : value.password
  };
}
