/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateSshKeyData
 */
export interface CreateSshKeyData {
  /**
   *
   * @type {string}
   * @memberof CreateSshKeyData
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof CreateSshKeyData
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateSshKeyData
   */
  value: string;
}

export function CreateSshKeyDataFromJSON(json: any): CreateSshKeyData {
  return CreateSshKeyDataFromJSONTyped(json, false);
}

export function CreateSshKeyDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSshKeyData {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userId: json["userId"],
    name: json["name"],
    value: json["value"]
  };
}

export function CreateSshKeyDataToJSON(value?: CreateSshKeyData | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userId: value.userId === undefined ? null : value.userId,
    name: value.name === undefined ? null : value.name,
    value: value.value === undefined ? null : value.value
  };
}
