/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateDepositRequest
 */
export interface CreateDepositRequest {
  /**
   *
   * @type {string}
   * @memberof CreateDepositRequest
   */
  amount: string;
}

export function CreateDepositRequestFromJSON(json: any): CreateDepositRequest {
  return CreateDepositRequestFromJSONTyped(json, false);
}

export function CreateDepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDepositRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    amount: json["amount"]
  };
}

export function CreateDepositRequestToJSON(value?: CreateDepositRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    amount: value.amount === undefined ? null : value.amount
  };
}
