/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DeleteProject
 */
export interface DeleteProject {
  /**
   *
   * @type {string}
   * @memberof DeleteProject
   */
  moveTo?: string;
}

export function DeleteProjectFromJSON(json: any): DeleteProject {
  return DeleteProjectFromJSONTyped(json, false);
}

export function DeleteProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteProject {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    moveTo: !exists(json, "moveTo") ? undefined : json["moveTo"]
  };
}

export function DeleteProjectToJSON(value?: DeleteProject | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    moveTo: value.moveTo === undefined ? null : value.moveTo
  };
}
