/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DepositConfig
 */
export interface DepositConfig {
  /**
   *
   * @type {string}
   * @memberof DepositConfig
   */
  minimalAmount: string;
}

export function DepositConfigFromJSON(json: any): DepositConfig {
  return DepositConfigFromJSONTyped(json, false);
}

export function DepositConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositConfig {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    minimalAmount: json["minimalAmount"]
  };
}

export function DepositConfigToJSON(value?: DepositConfig | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    minimalAmount: value.minimalAmount === undefined ? null : value.minimalAmount
  };
}
