/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Deposit
 */
export interface Deposit {
  /**
   *
   * @type {string}
   * @memberof Deposit
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Deposit
   */
  paymentId: string;
  /**
   *
   * @type {string}
   * @memberof Deposit
   */
  amount: string;
  /**
   *
   * @type {boolean}
   * @memberof Deposit
   */
  success: boolean;
}

export function DepositFromJSON(json: any): Deposit {
  return DepositFromJSONTyped(json, false);
}

export function DepositFromJSONTyped(json: any, ignoreDiscriminator: boolean): Deposit {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    paymentId: json["paymentId"],
    amount: json["amount"],
    success: json["success"]
  };
}

export function DepositToJSON(value?: Deposit | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    paymentId: value.paymentId === undefined ? null : value.paymentId,
    amount: value.amount === undefined ? null : value.amount,
    success: value.success === undefined ? null : value.success
  };
}
