/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Discount
 */
export interface Discount {
  /**
   *
   * @type {number}
   * @memberof Discount
   */
  period: number;
  /**
   *
   * @type {number}
   * @memberof Discount
   */
  percent: number;
}

export function DiscountFromJSON(json: any): Discount {
  return DiscountFromJSONTyped(json, false);
}

export function DiscountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discount {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    period: json["period"],
    percent: json["percent"]
  };
}

export function DiscountToJSON(value?: Discount | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    period: value.period === undefined ? null : value.period,
    percent: value.percent === undefined ? null : value.percent
  };
}
