/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum FinanceHistoryType {
  INVOICE = "INVOICE",
  AUTOPAYMENT = "AUTO_PAYMENT",
  DEPOSIT = "DEPOSIT",
  MANUALCHANGE = "MANUAL_CHANGE",
  EXTRAMONEY = "EXTRA_MONEY"
}

export function FinanceHistoryTypeFromJSON(json: any): FinanceHistoryType {
  return FinanceHistoryTypeFromJSONTyped(json, false);
}

export function FinanceHistoryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinanceHistoryType {
  return json as FinanceHistoryType;
}

export function FinanceHistoryTypeToJSON(value?: FinanceHistoryType | null): any {
  return value as any;
}
