/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InitiatePhoneChange
 */
export interface InitiatePhoneChange {
  /**
   *
   * @type {string}
   * @memberof InitiatePhoneChange
   */
  phone: string;
}

export function InitiatePhoneChangeFromJSON(json: any): InitiatePhoneChange {
  return InitiatePhoneChangeFromJSONTyped(json, false);
}

export function InitiatePhoneChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitiatePhoneChange {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    phone: json["phone"]
  };
}

export function InitiatePhoneChangeToJSON(value?: InitiatePhoneChange | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    phone: value.phone === undefined ? null : value.phone
  };
}
