/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  Invoice,
  InvoiceFromJSON,
  InvoiceFromJSONTyped,
  InvoiceToJSON,
  InvoiceDiscount,
  InvoiceDiscountFromJSON,
  InvoiceDiscountFromJSONTyped,
  InvoiceDiscountToJSON
} from "./";

/**
 *
 * @export
 * @interface InvoiceItem
 */
export interface InvoiceItem {
  /**
   *
   * @type {string}
   * @memberof InvoiceItem
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof InvoiceItem
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InvoiceItem
   */
  name: string;
  /**
   *
   * @type {object}
   * @memberof InvoiceItem
   */
  metadata: object;
  /**
   *
   * @type {InvoiceDiscount}
   * @memberof InvoiceItem
   */
  discount?: InvoiceDiscount;
  /**
   *
   * @type {number}
   * @memberof InvoiceItem
   */
  months?: number;
  /**
   *
   * @type {number}
   * @memberof InvoiceItem
   */
  days?: number;
  /**
   *
   * @type {Invoice}
   * @memberof InvoiceItem
   */
  invoice: Invoice;
}

export function InvoiceItemFromJSON(json: any): InvoiceItem {
  return InvoiceItemFromJSONTyped(json, false);
}

export function InvoiceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    amount: json["amount"],
    id: json["id"],
    name: json["name"],
    metadata: json["metadata"],
    discount: !exists(json, "discount") ? undefined : InvoiceDiscountFromJSON(json["discount"]),
    months: !exists(json, "months") ? undefined : json["months"],
    days: !exists(json, "days") ? undefined : json["days"],
    invoice: InvoiceFromJSON(json["invoice"])
  };
}

export function InvoiceItemToJSON(value?: InvoiceItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    amount: value.amount === undefined ? null : value.amount,
    id: value.id === undefined ? null : value.id,
    name: value.name === undefined ? null : value.name,
    metadata: value.metadata,
    discount: InvoiceDiscountToJSON(value.discount),
    months: value.months === undefined ? null : value.months,
    days: value.days === undefined ? null : value.days,
    invoice: InvoiceToJSON(value.invoice)
  };
}
