/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IP
 */
export interface IP {
  /**
   *
   * @type {string}
   * @memberof IP
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof IP
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof IP
   */
  dataCenterName: string;
  /**
   *
   * @type {number}
   * @memberof IP
   */
  version: number;
  /**
   *
   * @type {string}
   * @memberof IP
   */
  address: string;
  /**
   *
   * @type {string}
   * @memberof IP
   */
  reverseDns: string | undefined;
  /**
   *
   * @type {string}
   * @memberof IP
   */
  assignmentType: string;
  /**
   *
   * @type {string}
   * @memberof IP
   */
  assignmentId: string;
}

export function IPFromJSON(json: any): IP {
  return IPFromJSONTyped(json, false);
}

export function IPFromJSONTyped(json: any, ignoreDiscriminator: boolean): IP {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    dataCenterName: json["dataCenterName"],
    version: json["version"],
    address: json["address"],
    reverseDns: json["reverseDns"] === null ? undefined : json["reverseDns"],
    assignmentType: json["assignmentType"],
    assignmentId: json["assignmentId"]
  };
}

export function IPToJSON(value?: IP | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    userId: value.userId === undefined ? null : value.userId,
    dataCenterName: value.dataCenterName === undefined ? null : value.dataCenterName,
    version: value.version === undefined ? null : value.version,
    address: value.address === undefined ? null : value.address,
    reverseDns: value.reverseDns === undefined ? null : value.reverseDns,
    assignmentType: value.assignmentType === undefined ? null : value.assignmentType,
    assignmentId: value.assignmentId === undefined ? null : value.assignmentId
  };
}
