/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IpInvoiceId
 */
export interface IpInvoiceId {
  /**
   *
   * @type {string}
   * @memberof IpInvoiceId
   */
  value: string;
}

export function IpInvoiceIdFromJSON(json: any): IpInvoiceId {
  return IpInvoiceIdFromJSONTyped(json, false);
}

export function IpInvoiceIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpInvoiceId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"]
  };
}

export function IpInvoiceIdToJSON(value?: IpInvoiceId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value === undefined ? null : value.value
  };
}
