/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ManualDepositRequest
 */
export interface ManualDepositRequest {
  /**
   *
   * @type {string}
   * @memberof ManualDepositRequest
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof ManualDepositRequest
   */
  comment: string;
}

export function ManualDepositRequestFromJSON(json: any): ManualDepositRequest {
  return ManualDepositRequestFromJSONTyped(json, false);
}

export function ManualDepositRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManualDepositRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    amount: json["amount"],
    comment: json["comment"]
  };
}

export function ManualDepositRequestToJSON(value?: ManualDepositRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    amount: value.amount === undefined ? null : value.amount,
    comment: value.comment === undefined ? null : value.comment
  };
}
