/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ModulbankPayment
 */
export interface ModulbankPayment {
  /**
   *
   * @type {string}
   * @memberof ModulbankPayment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ModulbankPayment
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof ModulbankPayment
   */
  status: ModulbankPaymentStatusEnum;
  /**
   *
   * @type {object}
   * @memberof ModulbankPayment
   */
  paymentParams: object;
}

export function ModulbankPaymentFromJSON(json: any): ModulbankPayment {
  return ModulbankPaymentFromJSONTyped(json, false);
}

export function ModulbankPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModulbankPayment {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    amount: json["amount"],
    status: json["status"],
    paymentParams: json["paymentParams"]
  };
}

export function ModulbankPaymentToJSON(value?: ModulbankPayment | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    amount: value.amount === undefined ? null : value.amount,
    status: value.status === undefined ? null : value.status,
    paymentParams: value.paymentParams
  };
}

/**
 * @export
 * @enum {string}
 */
export enum ModulbankPaymentStatusEnum {
  WAIT = "WAIT",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED"
}
