/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Os
 */
export interface Os {
  /**
   *
   * @type {string}
   * @memberof Os
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Os
   */
  release: string;
  /**
   *
   * @type {string}
   * @memberof Os
   */
  distributor: string;
  /**
   *
   * @type {string}
   * @memberof Os
   */
  description: string;
}

export function OsFromJSON(json: any): Os {
  return OsFromJSONTyped(json, false);
}

export function OsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Os {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    release: json["release"],
    distributor: json["distributor"],
    description: json["description"]
  };
}

export function OsToJSON(value?: Os | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    release: value.release === undefined ? null : value.release,
    distributor: value.distributor === undefined ? null : value.distributor,
    description: value.description === undefined ? null : value.description
  };
}
