/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { PaymentAttempt, PaymentAttemptFromJSON, PaymentAttemptFromJSONTyped, PaymentAttemptToJSON } from "./";

/**
 *
 * @export
 * @interface Payment
 */
export interface Payment {
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  amount: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Payment
   */
  blacklist: Array<string>;
  /**
   *
   * @type {string}
   * @memberof Payment
   */
  status: PaymentStatusEnum;
  /**
   *
   * @type {Array<PaymentAttempt>}
   * @memberof Payment
   */
  attempts: Array<PaymentAttempt>;
}

export function PaymentFromJSON(json: any): Payment {
  return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    amount: json["amount"],
    blacklist: json["blacklist"],
    status: json["status"],
    attempts: (json["attempts"] as Array<any>).map(PaymentAttemptFromJSON)
  };
}

export function PaymentToJSON(value?: Payment | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    amount: value.amount === undefined ? null : value.amount,
    blacklist: value.blacklist === undefined ? null : value.blacklist,
    status: value.status === undefined ? null : value.status,
    attempts: (value.attempts as Array<any>).map(PaymentAttemptToJSON)
  };
}

/**
 * @export
 * @enum {string}
 */
export enum PaymentStatusEnum {
  WAIT = "WAIT",
  SUCCEEDED = "SUCCEEDED",
  CANCELED = "CANCELED"
}
