/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PaymentAttempt
 */
export interface PaymentAttempt {
  /**
   *
   * @type {string}
   * @memberof PaymentAttempt
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof PaymentAttempt
   */
  paymentSystem: string;
}

export function PaymentAttemptFromJSON(json: any): PaymentAttempt {
  return PaymentAttemptFromJSONTyped(json, false);
}

export function PaymentAttemptFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentAttempt {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    paymentSystem: json["paymentSystem"]
  };
}

export function PaymentAttemptToJSON(value?: PaymentAttempt | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    paymentSystem: value.paymentSystem === undefined ? null : value.paymentSystem
  };
}
