/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PaypalPayment
 */
export interface PaypalPayment {
  /**
   *
   * @type {string}
   * @memberof PaypalPayment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof PaypalPayment
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof PaypalPayment
   */
  status: PaypalPaymentStatusEnum;
  /**
   *
   * @type {string}
   * @memberof PaypalPayment
   */
  link: string;
}

export function PaypalPaymentFromJSON(json: any): PaypalPayment {
  return PaypalPaymentFromJSONTyped(json, false);
}

export function PaypalPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaypalPayment {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    amount: json["amount"],
    status: json["status"],
    link: json["link"]
  };
}

export function PaypalPaymentToJSON(value?: PaypalPayment | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    amount: value.amount === undefined ? null : value.amount,
    status: value.status === undefined ? null : value.status,
    link: value.link === undefined ? null : value.link
  };
}

/**
 * @export
 * @enum {string}
 */
export enum PaypalPaymentStatusEnum {
  WAIT = "WAIT",
  CAPTURED = "CAPTURED",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED"
}
