/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProBackupConfig
 */
export interface ProBackupConfig {
  /**
   *
   * @type {Array<number>}
   * @memberof ProBackupConfig
   */
  days: Array<number>;
}

export function ProBackupConfigFromJSON(json: any): ProBackupConfig {
  return ProBackupConfigFromJSONTyped(json, false);
}

export function ProBackupConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProBackupConfig {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    days: json["days"]
  };
}

export function ProBackupConfigToJSON(value?: ProBackupConfig | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    days: value.days === undefined ? null : value.days
  };
}
