/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Project
 */
export interface Project {
  /**
   *
   * @type {string}
   * @memberof Project
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof Project
   */
  imageId?: string;
  /**
   *
   * @type {Date}
   * @memberof Project
   */
  createdAt: Date;
}

export function ProjectFromJSON(json: any): Project {
  return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    name: json["name"],
    description: json["description"],
    imageId: !exists(json, "imageId") ? undefined : json["imageId"],
    createdAt: new Date(json["createdAt"])
  };
}

export function ProjectToJSON(value?: Project | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    userId: value.userId === undefined ? null : value.userId,
    name: value.name === undefined ? null : value.name,
    description: value.description === undefined ? null : value.description,
    imageId: value.imageId === undefined ? null : value.imageId,
    createdAt: value.createdAt.toISOString()
  };
}
