/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProjectId
 */
export interface ProjectId {
  /**
   *
   * @type {string}
   * @memberof ProjectId
   */
  id: string;
}

export function ProjectIdFromJSON(json: any): ProjectId {
  return ProjectIdFromJSONTyped(json, false);
}

export function ProjectIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"]
  };
}

export function ProjectIdToJSON(value?: ProjectId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id
  };
}
