/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Question
 */
export interface Question {
  /**
   *
   * @type {string}
   * @memberof Question
   */
  theme: string;
  /**
   *
   * @type {string}
   * @memberof Question
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Question
   */
  company: string;
  /**
   *
   * @type {string}
   * @memberof Question
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof Question
   */
  phone: string;
  /**
   *
   * @type {string}
   * @memberof Question
   */
  message: string;
}

export function QuestionFromJSON(json: any): Question {
  return QuestionFromJSONTyped(json, false);
}

export function QuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Question {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    theme: json["theme"],
    name: json["name"],
    company: json["company"],
    email: json["email"],
    phone: json["phone"],
    message: json["message"]
  };
}

export function QuestionToJSON(value?: Question | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    theme: value.theme === undefined ? null : value.theme,
    name: value.name === undefined ? null : value.name,
    company: value.company === undefined ? null : value.company,
    email: value.email === undefined ? null : value.email,
    phone: value.phone === undefined ? null : value.phone,
    message: value.message === undefined ? null : value.message
  };
}
