/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Rate
 */
export interface Rate {
  /**
   *
   * @type {string}
   * @memberof Rate
   */
  value: string;
}

export function RateFromJSON(json: any): Rate {
  return RateFromJSONTyped(json, false);
}

export function RateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"]
  };
}

export function RateToJSON(value?: Rate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value === undefined ? null : value.value
  };
}
