/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RestorePassword
 */
export interface RestorePassword {
  /**
   *
   * @type {string}
   * @memberof RestorePassword
   */
  email: string;
}

export function RestorePasswordFromJSON(json: any): RestorePassword {
  return RestorePasswordFromJSONTyped(json, false);
}

export function RestorePasswordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestorePassword {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json["email"]
  };
}

export function RestorePasswordToJSON(value?: RestorePassword | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email === undefined ? null : value.email
  };
}
