/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ServerInterfaceEndpoint
 */
export interface ServerInterfaceEndpoint {
  /**
   *
   * @type {number}
   * @memberof ServerInterfaceEndpoint
   */
  deviceId: number;
  /**
   *
   * @type {string}
   * @memberof ServerInterfaceEndpoint
   */
  deviceName: string;
  /**
   *
   * @type {string}
   * @memberof ServerInterfaceEndpoint
   */
  devicePrimaryIp4?: string;
  /**
   *
   * @type {string}
   * @memberof ServerInterfaceEndpoint
   */
  devicePrimaryIp6?: string;
  /**
   *
   * @type {string}
   * @memberof ServerInterfaceEndpoint
   */
  interfaceMac?: string;
  /**
   *
   * @type {number}
   * @memberof ServerInterfaceEndpoint
   */
  interfaceId: number;
  /**
   *
   * @type {string}
   * @memberof ServerInterfaceEndpoint
   */
  interfaceName: string;
}

export function ServerInterfaceEndpointFromJSON(json: any): ServerInterfaceEndpoint {
  return ServerInterfaceEndpointFromJSONTyped(json, false);
}

export function ServerInterfaceEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInterfaceEndpoint {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    deviceId: json["deviceId"],
    deviceName: json["deviceName"],
    devicePrimaryIp4: !exists(json, "devicePrimaryIp4") ? undefined : json["devicePrimaryIp4"],
    devicePrimaryIp6: !exists(json, "devicePrimaryIp6") ? undefined : json["devicePrimaryIp6"],
    interfaceMac: !exists(json, "interfaceMac") ? undefined : json["interfaceMac"],
    interfaceId: json["interfaceId"],
    interfaceName: json["interfaceName"]
  };
}

export function ServerInterfaceEndpointToJSON(value?: ServerInterfaceEndpoint | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    deviceId: value.deviceId === undefined ? null : value.deviceId,
    deviceName: value.deviceName === undefined ? null : value.deviceName,
    devicePrimaryIp4: value.devicePrimaryIp4 === undefined ? null : value.devicePrimaryIp4,
    devicePrimaryIp6: value.devicePrimaryIp6 === undefined ? null : value.devicePrimaryIp6,
    interfaceMac: value.interfaceMac === undefined ? null : value.interfaceMac,
    interfaceId: value.interfaceId === undefined ? null : value.interfaceId,
    interfaceName: value.interfaceName === undefined ? null : value.interfaceName
  };
}
