/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ServerConfig
 */
export interface ServerConfig {
  /**
   *
   * @type {string}
   * @memberof ServerConfig
   */
  cpu: string;
  /**
   *
   * @type {string}
   * @memberof ServerConfig
   */
  disk: string;
  /**
   *
   * @type {string}
   * @memberof ServerConfig
   */
  ram: string;
}

export function ServerConfigFromJSON(json: any): ServerConfig {
  return ServerConfigFromJSONTyped(json, false);
}

export function ServerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerConfig {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cpu: json["cpu"],
    disk: json["disk"],
    ram: json["ram"]
  };
}

export function ServerConfigToJSON(value?: ServerConfig | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cpu: value.cpu === undefined ? null : value.cpu,
    disk: value.disk === undefined ? null : value.disk,
    ram: value.ram === undefined ? null : value.ram
  };
}
