/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetUserPhone
 */
export interface SetUserPhone {
  /**
   *
   * @type {string}
   * @memberof SetUserPhone
   */
  phone: string;
}

export function SetUserPhoneFromJSON(json: any): SetUserPhone {
  return SetUserPhoneFromJSONTyped(json, false);
}

export function SetUserPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserPhone {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    phone: json["phone"]
  };
}

export function SetUserPhoneToJSON(value?: SetUserPhone | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    phone: value.phone === undefined ? null : value.phone
  };
}
