/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetUserName
 */
export interface SetUserName {
  /**
   *
   * @type {string}
   * @memberof SetUserName
   */
  name: string;
}

export function SetUserNameFromJSON(json: any): SetUserName {
  return SetUserNameFromJSONTyped(json, false);
}

export function SetUserNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserName {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"]
  };
}

export function SetUserNameToJSON(value?: SetUserName | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name === undefined ? null : value.name
  };
}
