/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SetUserEmail
 */
export interface SetUserEmail {
  /**
   *
   * @type {string}
   * @memberof SetUserEmail
   */
  email: string;
}

export function SetUserEmailFromJSON(json: any): SetUserEmail {
  return SetUserEmailFromJSONTyped(json, false);
}

export function SetUserEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserEmail {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json["email"]
  };
}

export function SetUserEmailToJSON(value?: SetUserEmail | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email === undefined ? null : value.email
  };
}
