/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SshKey
 */
export interface SshKey {
  /**
   *
   * @type {string}
   * @memberof SshKey
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof SshKey
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof SshKey
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SshKey
   */
  value: string;
}

export function SshKeyFromJSON(json: any): SshKey {
  return SshKeyFromJSONTyped(json, false);
}

export function SshKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SshKey {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    name: json["name"],
    value: json["value"]
  };
}

export function SshKeyToJSON(value?: SshKey | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    userId: value.userId === undefined ? null : value.userId,
    name: value.name === undefined ? null : value.name,
    value: value.value === undefined ? null : value.value
  };
}
