/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StripeCardClientSecret
 */
export interface StripeCardClientSecret {
  /**
   *
   * @type {string}
   * @memberof StripeCardClientSecret
   */
  value: string;
}

export function StripeCardClientSecretFromJSON(json: any): StripeCardClientSecret {
  return StripeCardClientSecretFromJSONTyped(json, false);
}

export function StripeCardClientSecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeCardClientSecret {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"]
  };
}

export function StripeCardClientSecretToJSON(value?: StripeCardClientSecret | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value === undefined ? null : value.value
  };
}
