/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface StripePayment
 */
export interface StripePayment {
  /**
   *
   * @type {string}
   * @memberof StripePayment
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof StripePayment
   */
  amount: string;
  /**
   *
   * @type {string}
   * @memberof StripePayment
   */
  status: StripePaymentStatusEnum;
  /**
   *
   * @type {string}
   * @memberof StripePayment
   */
  sessionId: string;
}

export function StripePaymentFromJSON(json: any): StripePayment {
  return StripePaymentFromJSONTyped(json, false);
}

export function StripePaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePayment {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    amount: json["amount"],
    status: json["status"],
    sessionId: json["sessionId"]
  };
}

export function StripePaymentToJSON(value?: StripePayment | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    amount: value.amount === undefined ? null : value.amount,
    status: value.status === undefined ? null : value.status,
    sessionId: value.sessionId === undefined ? null : value.sessionId
  };
}

/**
 * @export
 * @enum {string}
 */
export enum StripePaymentStatusEnum {
  WAIT = "WAIT",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED"
}
