/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SubscriptionSwitchToMonthly
 */
export interface SubscriptionSwitchToMonthly {
  /**
   *
   * @type {number}
   * @memberof SubscriptionSwitchToMonthly
   */
  period: number;
}

export function SubscriptionSwitchToMonthlyFromJSON(json: any): SubscriptionSwitchToMonthly {
  return SubscriptionSwitchToMonthlyFromJSONTyped(json, false);
}

export function SubscriptionSwitchToMonthlyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscriptionSwitchToMonthly {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    period: json["period"]
  };
}

export function SubscriptionSwitchToMonthlyToJSON(value?: SubscriptionSwitchToMonthly | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    period: value.period === undefined ? null : value.period
  };
}
