/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SubscriptionAction
 */
export interface SubscriptionAction {
  /**
   *
   * @type {string}
   * @memberof SubscriptionAction
   */
  type: SubscriptionActionTypeEnum;
  /**
   *
   * @type {string}
   * @memberof SubscriptionAction
   */
  invoiceId: string | undefined;
  /**
   *
   * @type {string}
   * @memberof SubscriptionAction
   */
  autoPaymentId: string | undefined;
  /**
   *
   * @type {string}
   * @memberof SubscriptionAction
   */
  adminId: string;
  /**
   *
   * @type {object}
   * @memberof SubscriptionAction
   */
  meta: object | undefined;
}

export function SubscriptionActionFromJSON(json: any): SubscriptionAction {
  return SubscriptionActionFromJSONTyped(json, false);
}

export function SubscriptionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionAction {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json["type"] === null ? undefined : json["type"],
    invoiceId: json["invoiceId"] === null ? undefined : json["invoiceId"],
    autoPaymentId: json["autoPaymentId"] === null ? undefined : json["autoPaymentId"],
    adminId: json["adminId"],
    meta: json["meta"]
  };
}

export function SubscriptionActionToJSON(value?: SubscriptionAction | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type === undefined ? null : value.type,
    invoiceId: value.invoiceId === undefined ? null : value.invoiceId,
    autoPaymentId: value.autoPaymentId === undefined ? null : value.autoPaymentId,
    adminId: value.adminId === undefined ? null : value.adminId,
    meta: value.meta
  };
}

/**
 * @export
 * @enum {string}
 */
export enum SubscriptionActionTypeEnum {
  Activate = "activate",
  Cancel = "cancel",
  Prolong = "prolong",
  AutoProlong = "auto-prolong",
  ItemsChange = "items-change",
  TypeChange = "type-change"
}
