/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Token
 */
export interface Token {
  /**
   *
   * @type {string}
   * @memberof Token
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof Token
   */
  refreshToken: string;
}

export function TokenFromJSON(json: any): Token {
  return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accessToken: json["accessToken"],
    refreshToken: json["refreshToken"]
  };
}

export function TokenToJSON(value?: Token | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    accessToken: value.accessToken === undefined ? null : value.accessToken,
    refreshToken: value.refreshToken === undefined ? null : value.refreshToken
  };
}
