/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VdsBackup
 */
export interface VdsBackup {
  /**
   *
   * @type {string}
   * @memberof VdsBackup
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof VdsBackup
   */
  createdAt: Date;
}

export function VdsBackupFromJSON(json: any): VdsBackup {
  return VdsBackupFromJSONTyped(json, false);
}

export function VdsBackupFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsBackup {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    createdAt: new Date(json["createdAt"])
  };
}

export function VdsBackupToJSON(value?: VdsBackup | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    createdAt: value.createdAt.toISOString()
  };
}
