/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VdsHistory
 */
export interface VdsHistory {
  /**
   *
   * @type {string}
   * @memberof VdsHistory
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof VdsHistory
   */
  vdsId: string;
  /**
   *
   * @type {Date}
   * @memberof VdsHistory
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof VdsHistory
   */
  type: VdsHistoryTypeEnum;
  /**
   *
   * @type {object}
   * @memberof VdsHistory
   */
  meta: object;
  /**
   *
   * @type {string}
   * @memberof VdsHistory
   */
  adminId: string;
  /**
   *
   * @type {boolean}
   * @memberof VdsHistory
   */
  isAdmin: boolean;
}

export function VdsHistoryFromJSON(json: any): VdsHistory {
  return VdsHistoryFromJSONTyped(json, false);
}

export function VdsHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsHistory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    vdsId: json["vdsId"],
    createdAt: new Date(json["createdAt"]),
    type: json["type"],
    meta: json["meta"],
    adminId: json["adminId"],
    isAdmin: json["isAdmin"]
  };
}

export function VdsHistoryToJSON(value?: VdsHistory | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    vdsId: value.vdsId === undefined ? null : value.vdsId,
    createdAt: value.createdAt.toISOString(),
    type: value.type === undefined ? null : value.type,
    meta: value.meta,
    adminId: value.adminId === undefined ? null : value.adminId,
    isAdmin: value.isAdmin === undefined ? null : value.isAdmin
  };
}

/**
 * @export
 * @enum {string}
 */
export enum VdsHistoryTypeEnum {
  Initialized = "initialized",
  Off = "off",
  On = "on",
  Reboot = "reboot",
  ProBackupEnabled = "pro_backup_enabled",
  ProBackupDisabled = "pro_backup_disabled",
  ProBackupConfigUpdated = "pro_backup_config_updated",
  RestoreFromBackup = "restore_from_backup",
  Reinstall = "reinstall",
  SwitchToMonthly = "switch_to_monthly",
  SwitchToHourly = "switch_to_hourly",
  TariffChanged = "tariff_changed",
  Deleted = "deleted",
  Renamed = " renamed",
  Moved = "moved",
  Prolonged = "prolonged"
}
