/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  ProBackupConfig,
  ProBackupConfigFromJSON,
  ProBackupConfigFromJSONTyped,
  ProBackupConfigToJSON,
  VncCredentials,
  VncCredentialsFromJSON,
  VncCredentialsFromJSONTyped,
  VncCredentialsToJSON
} from "./";

/**
 *
 * @export
 * @interface VdsInstance
 */
export interface VdsInstance {
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  userId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  subscriptionId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  projectId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  dataCenterId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  osId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  tariffId: string;
  /**
   *
   * @type {ProBackupConfig}
   * @memberof VdsInstance
   */
  proBackupConfig: ProBackupConfig;
  /**
   *
   * @type {Array<string>}
   * @memberof VdsInstance
   */
  sshKeyIds: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof VdsInstance
   */
  proBackupEnabled: boolean;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  primaryIp4: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  primaryIp6: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  hostname: string;
  /**
   *
   * @type {Date}
   * @memberof VdsInstance
   */
  createdAt: Date;
  /**
   *
   * @type {boolean}
   * @memberof VdsInstance
   */
  blocked: boolean;
  /**
   *
   * @type {string}
   * @memberof VdsInstance
   */
  blockReason?: string;
  /**
   *
   * @type {VncCredentials}
   * @memberof VdsInstance
   */
  vnc?: VncCredentials;
}

export function VdsInstanceFromJSON(json: any): VdsInstance {
  return VdsInstanceFromJSONTyped(json, false);
}

export function VdsInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsInstance {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    userId: json["userId"],
    subscriptionId: json["subscriptionId"],
    projectId: json["projectId"],
    dataCenterId: json["dataCenterId"],
    osId: json["osId"],
    tariffId: json["tariffId"],
    proBackupConfig: ProBackupConfigFromJSON(json["proBackupConfig"]),
    sshKeyIds: json["sshKeyIds"],
    proBackupEnabled: json["proBackupEnabled"],
    status: json["status"],
    primaryIp4: json["primaryIp4"],
    primaryIp6: json["primaryIp6"],
    name: json["name"],
    hostname: json["hostname"],
    createdAt: new Date(json["createdAt"]),
    blocked: json["blocked"],
    blockReason: !exists(json, "blockReason") ? undefined : json["blockReason"],
    vnc: !exists(json, "vnc") ? undefined : VncCredentialsFromJSON(json["vnc"])
  };
}

export function VdsInstanceToJSON(value?: VdsInstance | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    userId: value.userId === undefined ? null : value.userId,
    subscriptionId: value.subscriptionId === undefined ? null : value.subscriptionId,
    projectId: value.projectId === undefined ? null : value.projectId,
    dataCenterId: value.dataCenterId === undefined ? null : value.dataCenterId,
    osId: value.osId === undefined ? null : value.osId,
    tariffId: value.tariffId === undefined ? null : value.tariffId,
    proBackupConfig: ProBackupConfigToJSON(value.proBackupConfig),
    sshKeyIds: value.sshKeyIds === undefined ? null : value.sshKeyIds,
    proBackupEnabled: value.proBackupEnabled === undefined ? null : value.proBackupEnabled,
    status: value.status === undefined ? null : value.status,
    primaryIp4: value.primaryIp4 === undefined ? null : value.primaryIp4,
    primaryIp6: value.primaryIp6 === undefined ? null : value.primaryIp6,
    name: value.name === undefined ? null : value.name,
    hostname: value.hostname === undefined ? null : value.hostname,
    createdAt: value.createdAt.toISOString(),
    blocked: value.blocked === undefined ? null : value.blocked,
    blockReason: value.blockReason === undefined ? null : value.blockReason,
    vnc: VncCredentialsToJSON(value.vnc)
  };
}
