/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  ProBackupConfig,
  ProBackupConfigFromJSON,
  ProBackupConfigFromJSONTyped,
  ProBackupConfigToJSON,
  VdsConfig,
  VdsConfigFromJSON,
  VdsConfigFromJSONTyped,
  VdsConfigToJSON
} from "./";

/**
 *
 * @export
 * @interface VdsInstanceDto
 */
export interface VdsInstanceDto {
  /**
   *
   * @type {string}
   * @memberof VdsInstanceDto
   */
  projectId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstanceDto
   */
  dataCenterId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstanceDto
   */
  osId: string;
  /**
   *
   * @type {string}
   * @memberof VdsInstanceDto
   */
  tariffId: string;
  /**
   *
   * @type {boolean}
   * @memberof VdsInstanceDto
   */
  proBackupEnabled: boolean;
  /**
   *
   * @type {ProBackupConfig}
   * @memberof VdsInstanceDto
   */
  proBackupConfig: ProBackupConfig;
  /**
   *
   * @type {Array<string>}
   * @memberof VdsInstanceDto
   */
  sshKeyIds: Array<string>;
  /**
   *
   * @type {Array<VdsConfig>}
   * @memberof VdsInstanceDto
   */
  config: Array<VdsConfig>;
  /**
   *
   * @type {string}
   * @memberof VdsInstanceDto
   */
  subscriptionPeriod?: VdsInstanceDtoSubscriptionPeriodEnum;
  /**
   *
   * @type {string}
   * @memberof VdsInstanceDto
   */
  subscriptionType: VdsInstanceDtoSubscriptionTypeEnum;
}

export function VdsInstanceDtoFromJSON(json: any): VdsInstanceDto {
  return VdsInstanceDtoFromJSONTyped(json, false);
}

export function VdsInstanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsInstanceDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    projectId: json["projectId"],
    dataCenterId: json["dataCenterId"],
    osId: json["osId"],
    tariffId: json["tariffId"],
    proBackupEnabled: json["proBackupEnabled"],
    proBackupConfig: ProBackupConfigFromJSON(json["proBackupConfig"]),
    sshKeyIds: json["sshKeyIds"],
    config: (json["config"] as Array<any>).map(VdsConfigFromJSON),
    subscriptionPeriod: !exists(json, "subscriptionPeriod") ? undefined : json["subscriptionPeriod"],
    subscriptionType: json["subscriptionType"]
  };
}

export function VdsInstanceDtoToJSON(value?: VdsInstanceDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    projectId: value.projectId === undefined ? null : value.projectId,
    dataCenterId: value.dataCenterId === undefined ? null : value.dataCenterId,
    osId: value.osId === undefined ? null : value.osId,
    tariffId: value.tariffId === undefined ? null : value.tariffId,
    proBackupEnabled: value.proBackupEnabled === undefined ? null : value.proBackupEnabled,
    proBackupConfig: ProBackupConfigToJSON(value.proBackupConfig),
    sshKeyIds: value.sshKeyIds === undefined ? null : value.sshKeyIds,
    config: (value.config as Array<any>).map(VdsConfigToJSON),
    subscriptionPeriod: value.subscriptionPeriod === undefined ? null : value.subscriptionPeriod,
    subscriptionType: value.subscriptionType === undefined ? null : value.subscriptionType
  };
}

/**
 * @export
 * @enum {string}
 */
export enum VdsInstanceDtoSubscriptionPeriodEnum {
  MONTH = "MONTH",
  MONTH3 = "MONTH3",
  MONTH6 = "MONTH6",
  MONTH12 = "MONTH12"
}
/**
 * @export
 * @enum {string}
 */
export enum VdsInstanceDtoSubscriptionTypeEnum {
  Hourly = "hourly",
  Monthly = "monthly",
  MonthlyOnly = "monthly-only"
}
