/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VdsMove
 */
export interface VdsMove {
  /**
   *
   * @type {string}
   * @memberof VdsMove
   */
  projectId: string;
}

export function VdsMoveFromJSON(json: any): VdsMove {
  return VdsMoveFromJSONTyped(json, false);
}

export function VdsMoveFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsMove {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    projectId: json["projectId"]
  };
}

export function VdsMoveToJSON(value?: VdsMove | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    projectId: value.projectId === undefined ? null : value.projectId
  };
}
