/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VdsOrder
 */
export interface VdsOrder {
  /**
   *
   * @type {string}
   * @memberof VdsOrder
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof VdsOrder
   */
  subscriptionId: string;
  /**
   *
   * @type {string}
   * @memberof VdsOrder
   */
  invoiceId: string;
}

export function VdsOrderFromJSON(json: any): VdsOrder {
  return VdsOrderFromJSONTyped(json, false);
}

export function VdsOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsOrder {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    subscriptionId: json["subscriptionId"],
    invoiceId: json["invoiceId"]
  };
}

export function VdsOrderToJSON(value?: VdsOrder | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    subscriptionId: value.subscriptionId === undefined ? null : value.subscriptionId,
    invoiceId: value.invoiceId === undefined ? null : value.invoiceId
  };
}
