/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VdsTariffChange
 */
export interface VdsTariffChange {
  /**
   *
   * @type {string}
   * @memberof VdsTariffChange
   */
  tariffId: string;
}

export function VdsTariffChangeFromJSON(json: any): VdsTariffChange {
  return VdsTariffChangeFromJSONTyped(json, false);
}

export function VdsTariffChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsTariffChange {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    tariffId: json["tariffId"]
  };
}

export function VdsTariffChangeToJSON(value?: VdsTariffChange | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    tariffId: value.tariffId === undefined ? null : value.tariffId
  };
}
