/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VdsTariffDataCenter
 */
export interface VdsTariffDataCenter {
  /**
   *
   * @type {string}
   * @memberof VdsTariffDataCenter
   */
  dataCenterId: string;
  /**
   *
   * @type {number}
   * @memberof VdsTariffDataCenter
   */
  available: number;
}

export function VdsTariffDataCenterFromJSON(json: any): VdsTariffDataCenter {
  return VdsTariffDataCenterFromJSONTyped(json, false);
}

export function VdsTariffDataCenterFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsTariffDataCenter {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataCenterId: json["dataCenterId"],
    available: json["available"]
  };
}

export function VdsTariffDataCenterToJSON(value?: VdsTariffDataCenter | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dataCenterId: value.dataCenterId === undefined ? null : value.dataCenterId,
    available: value.available === undefined ? null : value.available
  };
}
