/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  VdsTariffDataCenter,
  VdsTariffDataCenterFromJSON,
  VdsTariffDataCenterFromJSONTyped,
  VdsTariffDataCenterToJSON
} from "./";

/**
 *
 * @export
 * @interface VdsTariff
 */
export interface VdsTariff {
  /**
   *
   * @type {string}
   * @memberof VdsTariff
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof VdsTariff
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof VdsTariff
   */
  cores: number;
  /**
   *
   * @type {number}
   * @memberof VdsTariff
   */
  ram: number;
  /**
   *
   * @type {number}
   * @memberof VdsTariff
   */
  storage: number;
  /**
   *
   * @type {number}
   * @memberof VdsTariff
   */
  instanceMonthPrice: string;
  /**
   *
   * @type {string}
   * @memberof VdsTariff
   */
  instanceHourPrice: string;
  /**
   *
   * @type {string}
   * @memberof VdsTariff
   */
  proBackupMonthPrice: string;
  /**
   *
   * @type {string}
   * @memberof VdsTariff
   */
  cpu: string;
  /**
   *
   * @type {string}
   * @memberof VdsTariff
   */
  proBackupHourPrice: string;
  /**
   *
   * @type {Array<VdsTariffDataCenter>}
   * @memberof VdsTariff
   */
  dataCenters: Array<VdsTariffDataCenter>;
}

export function VdsTariffFromJSON(json: any): VdsTariff {
  return VdsTariffFromJSONTyped(json, false);
}

export function VdsTariffFromJSONTyped(json: any, ignoreDiscriminator: boolean): VdsTariff {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    cores: json["cores"],
    ram: json["ram"],
    storage: json["storage"],
    instanceMonthPrice: json["instanceMonthPrice"],
    instanceHourPrice: json["instanceHourPrice"],
    proBackupMonthPrice: json["proBackupMonthPrice"],
    proBackupHourPrice: json["proBackupHourPrice"],
    cpu: json["cpu"],
    dataCenters: (json["dataCenters"] as Array<any>).map(VdsTariffDataCenterFromJSON)
  };
}

export function VdsTariffToJSON(value?: VdsTariff | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id === undefined ? null : value.id,
    name: value.name === undefined ? null : value.name,
    cores: value.cores === undefined ? null : value.cores,
    ram: value.ram === undefined ? null : value.ram,
    storage: value.storage === undefined ? null : value.storage,
    instanceMonthPrice: value.instanceMonthPrice === undefined ? null : value.instanceMonthPrice,
    instanceHourPrice: value.instanceHourPrice === undefined ? null : value.instanceHourPrice,
    proBackupMonthPrice: value.proBackupMonthPrice === undefined ? null : value.proBackupMonthPrice,
    proBackupHourPrice: value.proBackupHourPrice === undefined ? null : value.proBackupHourPrice,
    dataCenters: (value.dataCenters as Array<any>).map(VdsTariffDataCenterToJSON)
  };
}
