/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VncCredentials
 */
export interface VncCredentials {
  /**
   *
   * @type {string}
   * @memberof VncCredentials
   */
  host: string;
  /**
   *
   * @type {number}
   * @memberof VncCredentials
   */
  port: number;
  /**
   *
   * @type {string}
   * @memberof VncCredentials
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof VncCredentials
   */
  token: string;
}

export function VncCredentialsFromJSON(json: any): VncCredentials {
  return VncCredentialsFromJSONTyped(json, false);
}

export function VncCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): VncCredentials {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    host: json["host"],
    port: json["port"],
    password: json["password"],
    token: json["token"]
  };
}

export function VncCredentialsToJSON(value?: VncCredentials | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    host: value.host === undefined ? null : value.host,
    port: value.port === undefined ? null : value.port,
    password: value.password === undefined ? null : value.password,
    token: value.token === undefined ? null : value.token
  };
}
