/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WithdrawHours
 */
export interface WithdrawHours {
  /**
   *
   * @type {number}
   * @memberof WithdrawHours
   */
  hours: number;
  /**
   *
   * @type {string}
   * @memberof WithdrawHours
   */
  ticketId: string;
  /**
   *
   * @type {string}
   * @memberof WithdrawHours
   */
  reason: string;
}

export function WithdrawHoursFromJSON(json: any): WithdrawHours {
  return WithdrawHoursFromJSONTyped(json, false);
}

export function WithdrawHoursFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawHours {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hours: json["hours"],
    ticketId: json["ticketId"],
    reason: json["reason"]
  };
}

export function WithdrawHoursToJSON(value?: WithdrawHours | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    hours: value.hours === undefined ? null : value.hours,
    ticketId: value.ticketId === undefined ? null : value.ticketId,
    reason: value.reason === undefined ? null : value.reason
  };
}
