/* tslint:disable */
/* eslint-disable */
/**
 * Medialand API
 * Medialand API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import useSWR, { ConfigInterface } from "swr";

import {
  AdminVdsInstanceDto,
  AdminVdsInstanceDtoFromJSON,
  AdminVdsInstanceDtoToJSON,
  BlockVds,
  BlockVdsFromJSON,
  BlockVdsToJSON,
  DataCenter,
  DataCenterFromJSON,
  DataCenterToJSON,
  Os,
  OsFromJSON,
  OsToJSON,
  ProBackupConfig,
  ProBackupConfigFromJSON,
  ProBackupConfigToJSON,
  VdsHistory,
  VdsHistoryFromJSON,
  VdsHistoryToJSON,
  VdsInstance,
  VdsInstanceFromJSON,
  VdsInstanceToJSON,
  VdsInvoiceId,
  VdsInvoiceIdFromJSON,
  VdsInvoiceIdToJSON,
  VdsMove,
  VdsMoveFromJSON,
  VdsMoveToJSON,
  VdsOrder,
  VdsOrderFromJSON,
  VdsOrderToJSON,
  VdsReinstall,
  VdsReinstallFromJSON,
  VdsReinstallToJSON,
  VdsRename,
  VdsRenameFromJSON,
  VdsRenameToJSON,
  VdsTariff,
  VdsTariffFromJSON,
  VdsTariffToJSON,
  VdsTariffChange,
  VdsTariffChangeFromJSON,
  VdsTariffChangeToJSON
} from "../models";

interface VdsAvailableTariffsRequest {
  id: string;
}

interface VdsCreateRequest {
  adminVdsInstanceDto: AdminVdsInstanceDto;
}

interface VdsDeleteRequest {
  id: string;
}

interface VdsHistoryRequest {
  id: string;
}

interface VdsListRequest {
  projectId?: string;
  userId?: string;
}

interface VdsMoveRequest {
  id: string;
  vdsMove: VdsMove;
}

interface VdsOffRequest {
  id: string;
}

interface VdsOnRequest {
  id: string;
}

interface VdsProBackupConfigUpdateRequest {
  id: string;
  proBackupConfig: ProBackupConfig;
}

interface VdsProBackupDisableRequest {
  id: string;
}

interface VdsProBackupEnableRequest {
  id: string;
}

interface VdsRebootRequest {
  id: string;
}

interface VdsReinstallRequest {
  id: string;
  vdsReinstall: VdsReinstall;
}

interface VdsRenameRequest {
  id: string;
  vdsRename: VdsRename;
}

interface VdsTariffRequest {
  id: string;
}

interface VdsTariffChangeRequest {
  id: string;
  vdsTariffChange: VdsTariffChange;
}

interface VdsUnblockRequest {
  id: string;
}

interface VsdBlockRequest {
  id: string;
  blockVds: BlockVds;
}

/**
 *
 */
export class AdminVdsApi extends runtime.BaseAPI {
  /**
   */
  private async vdsAvailableTariffsRaw(
    requestParameters: VdsAvailableTariffsRequest
  ): Promise<runtime.ApiResponse<Array<VdsTariff>>> {
    this.vdsAvailableTariffsValidation(requestParameters);
    const context = this.vdsAvailableTariffsContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(VdsTariffFromJSON));
  }

  /**
   */
  private vdsAvailableTariffsValidation(requestParameters: VdsAvailableTariffsRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsAvailableTariffs."
      );
    }
  }

  /**
   */
  private vdsAvailableTariffsContext(requestParameters: VdsAvailableTariffsRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/tariff/{id}/available`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsAvailableTariffs = async (id: string): Promise<Array<VdsTariff>> => {
    const response = await this.vdsAvailableTariffsRaw({ id: id });
    return await response.value();
  };

  useVdsAvailableTariffs(id: string, config?: ConfigInterface<Array<VdsTariff>, Error>) {
    let valid = true;

    if (id === null || id === undefined || Number.isNaN(id)) {
      valid = false;
    }

    const context = this.vdsAvailableTariffsContext({ id: id! });
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsAvailableTariffs(id!) : undefined, config);
  }

  /**
   */
  private async vdsCreateRaw(requestParameters: VdsCreateRequest): Promise<runtime.ApiResponse<Array<VdsOrder>>> {
    this.vdsCreateValidation(requestParameters);
    const context = this.vdsCreateContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(VdsOrderFromJSON));
  }

  /**
   */
  private vdsCreateValidation(requestParameters: VdsCreateRequest) {
    if (requestParameters.adminVdsInstanceDto === null || requestParameters.adminVdsInstanceDto === undefined) {
      throw new runtime.RequiredError(
        "adminVdsInstanceDto",
        "Required parameter requestParameters.adminVdsInstanceDto was null or undefined when calling vdsCreate."
      );
    }
  }

  /**
   */
  private vdsCreateContext(requestParameters: VdsCreateRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance`,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: AdminVdsInstanceDtoToJSON(requestParameters.adminVdsInstanceDto)
    };
  }

  /**
   */
  vdsCreate = async (adminVdsInstanceDto: AdminVdsInstanceDto): Promise<Array<VdsOrder>> => {
    const response = await this.vdsCreateRaw({ adminVdsInstanceDto: adminVdsInstanceDto });
    return await response.value();
  };

  /**
   */
  private async vdsDataCentersRaw(): Promise<runtime.ApiResponse<Array<DataCenter>>> {
    this.vdsDataCentersValidation();
    const context = this.vdsDataCentersContext();
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(DataCenterFromJSON));
  }

  /**
   */
  private vdsDataCentersValidation() {}

  /**
   */
  private vdsDataCentersContext(): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/common/data-centers`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsDataCenters = async (): Promise<Array<DataCenter>> => {
    const response = await this.vdsDataCentersRaw();
    return await response.value();
  };

  useVdsDataCenters(config?: ConfigInterface<Array<DataCenter>, Error>) {
    let valid = true;

    const context = this.vdsDataCentersContext();
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsDataCenters() : undefined, config);
  }

  /**
   */
  private async vdsDeleteRaw(requestParameters: VdsDeleteRequest): Promise<runtime.ApiResponse<VdsInvoiceId>> {
    this.vdsDeleteValidation(requestParameters);
    const context = this.vdsDeleteContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => VdsInvoiceIdFromJSON(jsonValue));
  }

  /**
   */
  private vdsDeleteValidation(requestParameters: VdsDeleteRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsDelete."
      );
    }
  }

  /**
   */
  private vdsDeleteContext(requestParameters: VdsDeleteRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/delete`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsDelete = async (id: string): Promise<VdsInvoiceId> => {
    const response = await this.vdsDeleteRaw({ id: id });
    return await response.value();
  };

  /**
   */
  private async vdsHistoryRaw(requestParameters: VdsHistoryRequest): Promise<runtime.ApiResponse<Array<VdsHistory>>> {
    this.vdsHistoryValidation(requestParameters);
    const context = this.vdsHistoryContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(VdsHistoryFromJSON));
  }

  /**
   */
  private vdsHistoryValidation(requestParameters: VdsHistoryRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsHistory."
      );
    }
  }

  /**
   */
  private vdsHistoryContext(requestParameters: VdsHistoryRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/history`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsHistory = async (id: string): Promise<Array<VdsHistory>> => {
    const response = await this.vdsHistoryRaw({ id: id });
    return await response.value();
  };

  useVdsHistory(id: string, config?: ConfigInterface<Array<VdsHistory>, Error>) {
    let valid = true;

    if (id === null || id === undefined || Number.isNaN(id)) {
      valid = false;
    }

    const context = this.vdsHistoryContext({ id: id! });
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsHistory(id!) : undefined, config);
  }

  /**
   */
  private async vdsListRaw(requestParameters: VdsListRequest): Promise<runtime.ApiResponse<Array<VdsInstance>>> {
    this.vdsListValidation(requestParameters);
    const context = this.vdsListContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(VdsInstanceFromJSON));
  }

  /**
   */
  private vdsListValidation(requestParameters: VdsListRequest) {}

  /**
   */
  private vdsListContext(requestParameters: VdsListRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    if (requestParameters.projectId !== undefined) {
      queryParameters["projectId"] = requestParameters.projectId;
    }

    if (requestParameters.userId !== undefined) {
      queryParameters["userId"] = requestParameters.userId;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsList = async (projectId?: string, userId?: string): Promise<Array<VdsInstance>> => {
    const response = await this.vdsListRaw({ projectId: projectId, userId: userId });
    return await response.value();
  };

  useVdsList(projectId?: string, userId?: string, config?: ConfigInterface<Array<VdsInstance>, Error>) {
    let valid = true;

    const context = this.vdsListContext({ projectId: projectId!, userId: userId! });
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsList(projectId!, userId!) : undefined, config);
  }

  /**
   */
  private async vdsMoveRaw(requestParameters: VdsMoveRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsMoveValidation(requestParameters);
    const context = this.vdsMoveContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsMoveValidation(requestParameters: VdsMoveRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsMove."
      );
    }
    if (requestParameters.vdsMove === null || requestParameters.vdsMove === undefined) {
      throw new runtime.RequiredError(
        "vdsMove",
        "Required parameter requestParameters.vdsMove was null or undefined when calling vdsMove."
      );
    }
  }

  /**
   */
  private vdsMoveContext(requestParameters: VdsMoveRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/move`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: VdsMoveToJSON(requestParameters.vdsMove)
    };
  }

  /**
   */
  vdsMove = async (id: string, vdsMove: VdsMove): Promise<void> => {
    await this.vdsMoveRaw({ id: id, vdsMove: vdsMove });
  };

  /**
   */
  private async vdsOffRaw(requestParameters: VdsOffRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsOffValidation(requestParameters);
    const context = this.vdsOffContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsOffValidation(requestParameters: VdsOffRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsOff."
      );
    }
  }

  /**
   */
  private vdsOffContext(requestParameters: VdsOffRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/off`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsOff = async (id: string): Promise<void> => {
    await this.vdsOffRaw({ id: id });
  };

  /**
   */
  private async vdsOnRaw(requestParameters: VdsOnRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsOnValidation(requestParameters);
    const context = this.vdsOnContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsOnValidation(requestParameters: VdsOnRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsOn."
      );
    }
  }

  /**
   */
  private vdsOnContext(requestParameters: VdsOnRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/on`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsOn = async (id: string): Promise<void> => {
    await this.vdsOnRaw({ id: id });
  };

  /**
   */
  private async vdsOperatingSystemsRaw(): Promise<runtime.ApiResponse<Array<Os>>> {
    this.vdsOperatingSystemsValidation();
    const context = this.vdsOperatingSystemsContext();
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(OsFromJSON));
  }

  /**
   */
  private vdsOperatingSystemsValidation() {}

  /**
   */
  private vdsOperatingSystemsContext(): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/common/os`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsOperatingSystems = async (): Promise<Array<Os>> => {
    const response = await this.vdsOperatingSystemsRaw();
    return await response.value();
  };

  useVdsOperatingSystems(config?: ConfigInterface<Array<Os>, Error>) {
    let valid = true;

    const context = this.vdsOperatingSystemsContext();
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsOperatingSystems() : undefined, config);
  }

  /**
   */
  private async vdsProBackupConfigUpdateRaw(
    requestParameters: VdsProBackupConfigUpdateRequest
  ): Promise<runtime.ApiResponse<void>> {
    this.vdsProBackupConfigUpdateValidation(requestParameters);
    const context = this.vdsProBackupConfigUpdateContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsProBackupConfigUpdateValidation(requestParameters: VdsProBackupConfigUpdateRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsProBackupConfigUpdate."
      );
    }
    if (requestParameters.proBackupConfig === null || requestParameters.proBackupConfig === undefined) {
      throw new runtime.RequiredError(
        "proBackupConfig",
        "Required parameter requestParameters.proBackupConfig was null or undefined when calling vdsProBackupConfigUpdate."
      );
    }
  }

  /**
   */
  private vdsProBackupConfigUpdateContext(requestParameters: VdsProBackupConfigUpdateRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/pro-backup/config`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: ProBackupConfigToJSON(requestParameters.proBackupConfig)
    };
  }

  /**
   */
  vdsProBackupConfigUpdate = async (id: string, proBackupConfig: ProBackupConfig): Promise<void> => {
    await this.vdsProBackupConfigUpdateRaw({ id: id, proBackupConfig: proBackupConfig });
  };

  /**
   */
  private async vdsProBackupDisableRaw(
    requestParameters: VdsProBackupDisableRequest
  ): Promise<runtime.ApiResponse<VdsInvoiceId>> {
    this.vdsProBackupDisableValidation(requestParameters);
    const context = this.vdsProBackupDisableContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => VdsInvoiceIdFromJSON(jsonValue));
  }

  /**
   */
  private vdsProBackupDisableValidation(requestParameters: VdsProBackupDisableRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsProBackupDisable."
      );
    }
  }

  /**
   */
  private vdsProBackupDisableContext(requestParameters: VdsProBackupDisableRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/pro-backup/disable`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsProBackupDisable = async (id: string): Promise<VdsInvoiceId> => {
    const response = await this.vdsProBackupDisableRaw({ id: id });
    return await response.value();
  };

  /**
   */
  private async vdsProBackupEnableRaw(
    requestParameters: VdsProBackupEnableRequest
  ): Promise<runtime.ApiResponse<VdsInvoiceId>> {
    this.vdsProBackupEnableValidation(requestParameters);
    const context = this.vdsProBackupEnableContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => VdsInvoiceIdFromJSON(jsonValue));
  }

  /**
   */
  private vdsProBackupEnableValidation(requestParameters: VdsProBackupEnableRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsProBackupEnable."
      );
    }
  }

  /**
   */
  private vdsProBackupEnableContext(requestParameters: VdsProBackupEnableRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/pro-backup/enable`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsProBackupEnable = async (id: string): Promise<VdsInvoiceId> => {
    const response = await this.vdsProBackupEnableRaw({ id: id });
    return await response.value();
  };

  /**
   */
  private async vdsRebootRaw(requestParameters: VdsRebootRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsRebootValidation(requestParameters);
    const context = this.vdsRebootContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsRebootValidation(requestParameters: VdsRebootRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsReboot."
      );
    }
  }

  /**
   */
  private vdsRebootContext(requestParameters: VdsRebootRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/reboot`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsReboot = async (id: string): Promise<void> => {
    await this.vdsRebootRaw({ id: id });
  };

  /**
   */
  private async vdsReinstallRaw(requestParameters: VdsReinstallRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsReinstallValidation(requestParameters);
    const context = this.vdsReinstallContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsReinstallValidation(requestParameters: VdsReinstallRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsReinstall."
      );
    }
    if (requestParameters.vdsReinstall === null || requestParameters.vdsReinstall === undefined) {
      throw new runtime.RequiredError(
        "vdsReinstall",
        "Required parameter requestParameters.vdsReinstall was null or undefined when calling vdsReinstall."
      );
    }
  }

  /**
   */
  private vdsReinstallContext(requestParameters: VdsReinstallRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/reinstall`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: VdsReinstallToJSON(requestParameters.vdsReinstall)
    };
  }

  /**
   */
  vdsReinstall = async (id: string, vdsReinstall: VdsReinstall): Promise<void> => {
    await this.vdsReinstallRaw({ id: id, vdsReinstall: vdsReinstall });
  };

  /**
   */
  private async vdsRenameRaw(requestParameters: VdsRenameRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsRenameValidation(requestParameters);
    const context = this.vdsRenameContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsRenameValidation(requestParameters: VdsRenameRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsRename."
      );
    }
    if (requestParameters.vdsRename === null || requestParameters.vdsRename === undefined) {
      throw new runtime.RequiredError(
        "vdsRename",
        "Required parameter requestParameters.vdsRename was null or undefined when calling vdsRename."
      );
    }
  }

  /**
   */
  private vdsRenameContext(requestParameters: VdsRenameRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/rename`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: VdsRenameToJSON(requestParameters.vdsRename)
    };
  }

  /**
   */
  vdsRename = async (id: string, vdsRename: VdsRename): Promise<void> => {
    await this.vdsRenameRaw({ id: id, vdsRename: vdsRename });
  };

  /**
   */
  private async vdsTariffRaw(requestParameters: VdsTariffRequest): Promise<runtime.ApiResponse<VdsTariff>> {
    this.vdsTariffValidation(requestParameters);
    const context = this.vdsTariffContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => VdsTariffFromJSON(jsonValue));
  }

  /**
   */
  private vdsTariffValidation(requestParameters: VdsTariffRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsTariff."
      );
    }
  }

  /**
   */
  private vdsTariffContext(requestParameters: VdsTariffRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/tariff/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsTariff = async (id: string): Promise<VdsTariff> => {
    const response = await this.vdsTariffRaw({ id: id });
    return await response.value();
  };

  useVdsTariff(id: string, config?: ConfigInterface<VdsTariff, Error>) {
    let valid = true;

    if (id === null || id === undefined || Number.isNaN(id)) {
      valid = false;
    }

    const context = this.vdsTariffContext({ id: id! });
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsTariff(id!) : undefined, config);
  }

  /**
   */
  private async vdsTariffChangeRaw(
    requestParameters: VdsTariffChangeRequest
  ): Promise<runtime.ApiResponse<VdsInvoiceId>> {
    this.vdsTariffChangeValidation(requestParameters);
    const context = this.vdsTariffChangeContext(requestParameters);
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => VdsInvoiceIdFromJSON(jsonValue));
  }

  /**
   */
  private vdsTariffChangeValidation(requestParameters: VdsTariffChangeRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsTariffChange."
      );
    }
    if (requestParameters.vdsTariffChange === null || requestParameters.vdsTariffChange === undefined) {
      throw new runtime.RequiredError(
        "vdsTariffChange",
        "Required parameter requestParameters.vdsTariffChange was null or undefined when calling vdsTariffChange."
      );
    }
  }

  /**
   */
  private vdsTariffChangeContext(requestParameters: VdsTariffChangeRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/tariff`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: VdsTariffChangeToJSON(requestParameters.vdsTariffChange)
    };
  }

  /**
   */
  vdsTariffChange = async (id: string, vdsTariffChange: VdsTariffChange): Promise<VdsInvoiceId> => {
    const response = await this.vdsTariffChangeRaw({ id: id, vdsTariffChange: vdsTariffChange });
    return await response.value();
  };

  /**
   */
  private async vdsTariffsRaw(): Promise<runtime.ApiResponse<Array<VdsTariff>>> {
    this.vdsTariffsValidation();
    const context = this.vdsTariffsContext();
    const response = await this.request(context);

    return new runtime.JSONApiResponse(response, jsonValue => jsonValue.map(VdsTariffFromJSON));
  }

  /**
   */
  private vdsTariffsValidation() {}

  /**
   */
  private vdsTariffsContext(): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/tariff`,
      method: "GET",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsTariffs = async (): Promise<Array<VdsTariff>> => {
    const response = await this.vdsTariffsRaw();
    return await response.value();
  };

  useVdsTariffs(config?: ConfigInterface<Array<VdsTariff>, Error>) {
    let valid = true;

    const context = this.vdsTariffsContext();
    const { headers, ...swrKey } = context;
    return useSWR(JSON.stringify(swrKey), valid ? () => this.vdsTariffs() : undefined, config);
  }

  /**
   */
  private async vdsUnblockRaw(requestParameters: VdsUnblockRequest): Promise<runtime.ApiResponse<void>> {
    this.vdsUnblockValidation(requestParameters);
    const context = this.vdsUnblockContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vdsUnblockValidation(requestParameters: VdsUnblockRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vdsUnblock."
      );
    }
  }

  /**
   */
  private vdsUnblockContext(requestParameters: VdsUnblockRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/unblock`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(requestParameters.id))
      ),
      method: "POST",
      headers: headerParameters,
      query: queryParameters
    };
  }

  /**
   */
  vdsUnblock = async (id: string): Promise<void> => {
    await this.vdsUnblockRaw({ id: id });
  };

  /**
   */
  private async vsdBlockRaw(requestParameters: VsdBlockRequest): Promise<runtime.ApiResponse<void>> {
    this.vsdBlockValidation(requestParameters);
    const context = this.vsdBlockContext(requestParameters);
    const response = await this.request(context);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  private vsdBlockValidation(requestParameters: VsdBlockRequest) {
    if (requestParameters.id === null || requestParameters.id === undefined) {
      throw new runtime.RequiredError(
        "id",
        "Required parameter requestParameters.id was null or undefined when calling vsdBlock."
      );
    }
    if (requestParameters.blockVds === null || requestParameters.blockVds === undefined) {
      throw new runtime.RequiredError(
        "blockVds",
        "Required parameter requestParameters.blockVds was null or undefined when calling vsdBlock."
      );
    }
  }

  /**
   */
  private vsdBlockContext(requestParameters: VsdBlockRequest): runtime.RequestOpts {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = typeof token === "function" ? token("bearer", []) : token;

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    return {
      path: `/api/admin/vds/instance/{id}/block`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: BlockVdsToJSON(requestParameters.blockVds)
    };
  }

  /**
   */
  vsdBlock = async (id: string, blockVds: BlockVds): Promise<void> => {
    await this.vsdBlockRaw({ id: id, blockVds: blockVds });
  };
}
